### PR TITLE
Corrected links and added placement coordinators in contact section

### PR DESCRIPTION
**Pull request by ahujatejas06**
closes#39
closes#41

added placement coordinators link in footer section and renamed the files...

### CODE REVIEW

**Comment by ahujatejas06** [comment]
closes #39
closes #41

added placement coordinators link in footer section and renamed the files...

It is compiling on my laptop locally but vercel says failed to deploy...

**Comment by abhishekshree** [comment]
@ahujatejas06 renaming just the pages changes the endpoint too, so you'll have to change the endpoint names everywhere otherwise routing will fail, example: contact button the index page right now.

**Review by abhishekshree — CHANGES_REQUESTED** [review]
Fix broken links after file renaming

**Comment by 1-Harshit** [comment]
Time to google how to fix conflicts

**Comment by ahujatejas06** [comment]
closes https://github.com/abhishekshree/spo-website/issues/39
closes https://github.com/abhishekshree/spo-website/issues/41

added placement coordinators link in footer section and renamed the files...

**Pull request closed without merging**
