### PR TITLE
Home page changes

### PR DESCRIPTION
**Pull request by utkarsh-tf141**
Will add the Announcement and Events after issue  #85

### CODE REVIEW

**Comment by 1-Harshit** [comment]
iframe dalna tha link nhi
image

What is this *?
image

Make carousel  move automatically

then we're good to go

**Comment by 1-Harshit** [comment]
image
fix it's width

**Comment by 1-Harshit** [comment]
- [ ] Make a new issue for Announcement and Events referencing #85 and #89
- [ ] Fix the width and that "*" 
- [ ] Try to move Slider automatically
- [ ] Swap position of sliders and why recruit

Post this I'll merge this, Good job

**Comment by itsGyanendra** [comment]
### Why Recruit from IIT Kanpur ?
Make the heading center align.
Add images also in card as shown in below template
image

**Comment by utkarsh-tf141** [comment]
Will add images along with the next issue

**Comment by utkarsh-tf141** [comment]
-closes #83

**Comment by itsGyanendra** [comment]
@utkarsh-tf141 

- [ ] Center the title News@IITK
- [ ] Increase the size of Heading Past Recruiters
- [ ]  Check responsiveness of homepage currently it seems unresponsive

**Comment by itsGyanendra** [comment]
image
Iframe get vanishes once you navigate to another page and then come back to homepage.

**Comment by utkarsh-tf141** [comment]
Finding fix for the iframe issue
Also tell what to add in alumni card description?

**Pull request closed without merging**
