### PR TITLE
Links Updated

### PR DESCRIPTION
**Pull request by ahujatejas06**
Couldn't find the brochure of MTH Branch
closes#28

### CODE REVIEW

**Comment by abhishekshree** [comment]
LGTM

**Comment by abhishekshree** [comment]
https://spo.iitk.ac.in/assets/docs/2019-20/Brochure_MTH.pdf, here's brochure for MTH @ahujatejas06

**Comment by ahujatejas06** [comment]
Added MTH Brochure 
closes#28

**Comment by 1-Harshit** [comment]
@ahujatejas06 it is `- closes #28` you're missing the space
- closes #28

**Pull request merged**
