### PR TITLE
added previous year team links and added pyt pages too

### LINKED ISSUE #6: Make appropriate UI for the past teams section in student-team page

### PR DESCRIPTION
**Pull request by amdpt323**
-m closes #6

### CODE REVIEW

**Comment by abhishekshree** [comment]
A lot of members have been skipped here, see https://spo.iitk.ac.in/team_2016.html, and see https://spo-git-fork-amdpt323-pyt2-abhishekshree.vercel.app/student-team/2016-17

We can not leave any member from the team, change the title if such cases exist

**Review by abhishekshree — CHANGES_REQUESTED** [review]
Complete team members are needed here.

**Comment by 1-Harshit** [comment]
> Complete team members are needed here.

I guess Just names / linkedin of OPC should be enough?

**Comment by abhishekshree** [comment]
> > Complete team members are needed here.
> 
> I guess Just names / linkedin of OPC should be enough?

I am not sure about this though, need to ask some OPC, merging until then

**Pull request merged**
